// ============================================
// Configuration & Global Variables
// ============================================

// Application State - Trading
let trades = [];
let notes = [];
let dailyFees = {};

// Date Management
let currentTradingDate = null; 
let calendarDate = new Date();
let calendarStartDate = null;
let calendarEndDate = null;
let selectedCalendarDay = null;
// UI State
let isSelecting = false;
let timeEditMode = false;
let currentLanguage = 'en';

// Analytics State
let analyticsPeriod = 'all';
let dashboardStartDate = null;
let dashboardEndDate = null;
let analyticsStartDate = null;
let analyticsEndDate = null;
let tradesStartDate = null;
let tradesEndDate = null;
let currentAnalyticsSection = 'detail';

// Notes State
let editingNoteId = null;
let currentNotesSection = 'all';
let currentViewingNoteId = null;
let currentTextColor = '#e4e4e7';
let currentFont = "'Inter', sans-serif";

// Psychology State
let psychologyData = {};
let currentPsychologySection = 'input';
let currentPsychologyDate = null;

// Calendar State
let selectedWeekPnl = null;
let selectedMonthYear = null;
let selectedMonth = null;

// Trade Selection State
let selectedTradesList = new Set();
let selectedTrades = new Set();

// Dashboard State
let currentDashboardSection = 'trading';
let selectedKellyMultiplier = 0.1;

// Chart instances
let basicCharts = {};
let advancedCharts = {};

// Window-level chart instance for psychology
if (typeof window !== 'undefined') {
    window.psychologyChart = null;
}

// ============================================
// Language Translations
// ============================================

const translations = {
    en: {
        'dashboard': 'Dashboard',
        'calendar': 'Calendar View',
        'analytics': 'Analytics',
        'notes': 'Notes',
        'tradelist': 'Trade List',
        'settings': 'Settings',
        'dashboard-title': 'Trading Dashboard',
        'dashboard-subtitle': 'Track your trades and performance',
        'language': 'Language:',
        'total-pl': 'Total P/L',
        'net-result': 'Net Result',
        'trades': 'Trades',
        'total-count': 'Total Count',
        'win-rate': 'Win Rate',
        'record-trade': 'Record Trade',
        'symbol': 'Symbol',
        'shares': 'Shares',
        'buy-price': 'Buy Price',
        'sell-price': 'Sell Price',
        'return-pct': 'Return %',
        'pnl': 'P&L',
        'entry-time': 'Entry Time',
        'exit-time': 'Exit Time',
        'holding-time': 'Holding Time',
        'edit': 'Edit',
        'auto': 'Auto',
        'reset': 'Reset',
        'add-trade': 'Add Trade',
        'performance': 'Performance',
        'best-trade': 'Best Trade',
        'worst-trade': 'Worst Trade',
        'avg-win': 'Avg Win',
        'avg-loss': 'Avg Loss',
        'total-invested': 'Total Invested',
        'profit-factor': 'Profit Factor',
        'trade-history': 'Trade History',
        'date': 'Date',
        'time': 'Time',
        'actions': 'Actions',
        'no-trades': 'No trades recorded yet',
        'calendar-title': 'Calendar View',
        'calendar-subtitle': 'Visualize your trading performance over time',
        'clear-selection': 'Clear Selection',
        'calendar-help': 'Click and drag on calendar to select date range, or click on a day to see details',
        'selected-period': 'Selected Period',
        'total-trades': 'Total Trades',
        'avg-daily-pl': 'Avg Daily P/L',
        'best-day': 'Best Day',
        'worst-day': 'Worst Day',
        'weekly-pl': 'Weekly P/L',
        'analytics-title': 'Trading Analytics',
        'notes-title': 'Trading Notes',
        'notes-subtitle': 'Document your trading insights and thoughts',
        'new-note': 'New Note',
        'note-title-placeholder': 'Enter note title...',
        'note-content-placeholder': 'Write your note here...',
        'cancel': 'Cancel',
        'save-note': 'Save Note',
        'no-notes': 'No notes written yet. Click "New Note" to start.',
        'daily-review': 'Daily Review',
        'strategy': 'Strategy',
        'general': 'General',
        'no-daily-notes': 'No daily review notes yet. Click "New Note" to start.',
        'no-strategy-notes': 'No strategy notes yet. Click "New Note" to start.',
        'no-general-notes': 'No general notes yet. Click "New Note" to start.',
        'tradelist-title': 'Trade List',
        'tradelist-subtitle': 'Complete list of all your trades',
        'settings-title': 'Settings',
        'settings-subtitle': 'Configure your trading journal preferences',
        'general-settings': 'General Settings',
        'default-language': 'Default Language',
        'data-management': 'Data Management',
        'export-data': 'Export Data',
        'import-data': 'Import Data',
        'danger-zone': 'Danger Zone',
        'clear-all-data': 'Clear All Data',
        'all-time': 'All Time',
        'this-month': 'This Month',
        'this-week': 'This Week',
        'today': 'Today',
        'detail': 'Detail',
        'charts': 'Charts',
        'net-profit': 'Net Profit',
        'largest-win': 'Largest Win',
        'largest-loss': 'Largest Loss',
        'performance-summary': 'Performance Summary',
        'trading-performance': 'Trading Performance',
        'total-gain': 'Total Gain',
        'total-loss': 'Total Loss',
        'total-fees': 'Total Fees',
        'total-volume': 'Total Volume',
        'win-loss-stats': 'Win/Loss Statistics',
        'winning-trades': 'Winning Trades',
        'losing-trades': 'Losing Trades',
        'avg-winning-trade': 'Avg Winning Trade',
        'avg-losing-trade': 'Avg Losing Trade',
        'daily-performance': 'Daily Performance',
        'daily-per-win': 'Daily P&L per Win',
        'daily-per-loss': 'Daily P&L per Loss',
        'daily-per-fees': 'Daily Fees per Day',
        'best-trading-day': 'Best Trading Day',
        'worst-trading-day': 'Worst Trading Day',
        'time-analysis': 'Time Analysis',
        'avg-hold-time': 'Avg Hold Time',
        'shortest-hold': 'Shortest Hold',
        'longest-hold': 'Longest Hold',
        'best-trading-hour': 'Best Trading Hour',
        'worst-trading-hour': 'Worst Trading Hour',
        'best-day-week': 'Best Day of Week',
        'trading-activity': 'Trading Activity',
        'trading-days': 'Trading Days',
        'avg-trades-per-day': 'Avg Trades per Day',
        'max-trades-day': 'Max Trades in Day',
        'avg-position-size': 'Avg Position Size',
        'largest-position': 'Largest Position',
        'smallest-position': 'Smallest Position',
        'streak-analysis': 'Streak Analysis',
        'current-streak': 'Current Streak',
        'max-win-streak': 'Max Win Streak',
        'max-loss-streak': 'Max Loss Streak',
        'current-win-streak': 'Current Win Streak',
        'current-loss-streak': 'Current Loss Streak',
        'avg-win-streak': 'Avg Win Streak',
        'symbol-performance': 'Symbol Performance',
        'most-profitable-symbol': 'Most Profitable',
        'least-profitable-symbol': 'Least Profitable',
        'most-traded-symbol': 'Most Traded',
        'unique-symbols': 'Unique Symbols',
        'symbol-win-rate': 'Best Symbol Win Rate',
        'symbol-avg-return': 'Best Symbol Avg Return',
        'risk-management': 'Risk Management',
        'max-drawdown': 'Max Drawdown',
        'current-drawdown': 'Current Drawdown',
        'recovery-factor': 'Recovery Factor',
        'max-daily-loss': 'Max Daily Loss',
        'max-daily-gain': 'Max Daily Gain',
        'risk-reward-ratio': 'Avg Risk/Reward',
        'daily-fees': 'Daily Fees',
        'basic-charts': 'Basic Performance Charts',
        'cumulative-pl': 'Cumulative P&L',
        'win-loss-ratio': 'Win/Loss Distribution',
        'daily-pl': 'Daily P&L',
        'monthly-performance': 'Monthly Performance',
        'equity-curve': 'Equity Curve',
        'drawdown-chart': 'Drawdown Analysis',
        'symbol-performance-chart': 'Symbol Performance',
        'time-distribution': 'Time Distribution',
        'return-distribution': 'Return Distribution',
        'rolling-performance': 'Rolling Performance',
        'volume-analysis': 'Volume Analysis',
        'correlation-matrix': 'Performance Correlation',
        'volatility-analysis': 'Volatility Analysis',
        'risk-return-scatter': 'Risk-Return Scatter',
        'performance-attribution': 'Performance Attribution',
        'trade-duration-analysis': 'Trade Duration Analysis',
        'pl-heatmap': 'P&L Heatmap',
        'win-rate-by-time': 'Win Rate by Time',
        'position-sizing-analysis': 'Position Sizing Analysis',
        'trading-efficiency-metrics': 'Trading Efficiency Metrics',
        'all-notes': 'All',
        'back': 'Back',
        'show-more': 'Show more',
        'show-less': 'Show less',
        'position-calculator': 'Position Calculator',
        'kelly-criterion-calculator': 'Kelly Criterion Calculator',
        'account-balance': 'Account Balance ($)',
        'win-rate-input': 'Win Rate (%)',
        'average-win': 'Average Win ($)',
        'average-loss': 'Average Loss ($)',
        'auto-load-trade-data': 'Auto Load from Trade History',
        'kelly-percentage': 'Kelly Percentage',
        'full-kelly-position': 'Full Kelly Position',
        'quarter-kelly': 'Quarter Kelly (25%)',
        'tenth-kelly': 'Tenth Kelly (10%)',
        'ultra-safe': 'Ultra Safe',
        'conservative': 'Conservative',
        'moderate': 'Moderate',
        'position-analysis': 'Position Analysis',
        'recommended-size': 'Recommended Size',
        'account-utilization': 'Account Utilization',
        'expected-value': 'Expected Value',
        'auto-analysis': 'Auto Analysis',
        'recent-win-rate': 'Recent Win Rate',
        'pl-ratio': 'P&L Ratio',
        'kelly-status': 'Kelly Status',
        'safe': 'Safe',
        'medium': 'Medium',
        'high': 'High',
        'kelly-calculator': 'Kelly Calculator',
        'risk-calculator': 'Risk Calculator',
        'risk-percentage': 'Risk Percentage (%)',
        'entry-price': 'Entry Price ($)',
        'stop-loss-price': 'Stop Loss Price ($)',
        'position-size': 'Position Size',
        'shares-quantity': 'Shares Quantity',
        'risk-per-share': 'Risk per Share',
        'max-loss': 'Max Loss',
        'breakeven-move': 'Breakeven Move',
        'risk-amount': 'Risk Amount',
        'kelly-strategies': 'Position Sizing Strategies',
        'risk-analysis': 'Risk Analysis',
        'position-cost': 'Position Cost',
        'risk-ratio': 'Risk Ratio',
        'stop-distance': 'Stop Distance',
        'risk-management-calculator': 'Risk Management Calculator',
        'risk-presets': 'Risk Ratio',
        'trading-record': 'Trading Record',
        'amount': 'Amount ($)',
        'psychology': 'Psychology',
        'psychology-title': 'Trading Psychology',
        'psychology-subtitle': 'Analyze and optimize your trading psychology',
        'daily-psychology-input': 'Daily Psychology Input',
        'biological-rhythm': 'Biological Rhythm',
        'sleep-hours': 'Sleep Hours',
        'sleep-quality': 'Sleep Quality',
        'caffeine-intake': 'Caffeine Intake (mg)',
        'energy-level': 'Energy Level',
        'time-environment': 'Time & Environment',
        'planned-start-time': 'Planned Start Time',
        'actual-start-time': 'Actual Start Time',
        'market-delay': 'Market Open Delay (min)',
        'trading-environment': 'Trading Environment',
        'economic-pressure': 'Economic Pressure',
        'account-balance-psych': 'Account Balance ($)',
        'pressure-level': 'Financial Pressure Level',
        'daily-target': 'Daily P&L Target ($)',
        'max-daily-loss': 'Max Daily Loss Limit ($)',
        'emotional-state': 'Emotional State',
        'pre-market-mood': 'Pre-Market Mood',
        'confidence-level': 'Confidence Level',
        'stress-level': 'Stress Level',
        'focus-level': 'Focus Level',
        'save-psychology-data': 'Save Psychology Data',
        'psychology-metrics': 'Psychology Metrics',
        'daily-psych-score': 'Daily Psychology Score',
        'sleep-factor': 'Sleep Factor',
        'stress-factor': 'Stress Factor',
        'environment-factor': 'Environment Factor',
        'pressure-index': 'Pressure Index',
        'emotional-readiness': 'Emotional Readiness',
        'psychology-insights': 'Psychology Insights & Recommendations',
        'no-psychology-data': 'No psychology data available. Fill in today\'s data to get insights.',
        'start-time': 'Start Time',
        'reset-psychology-data': 'Reset Data',
        'psychology-analysis': 'Psychology Analysis',
        'annual-trading-overview': 'Annual Trading Overview',
        'week-pnl': 'Week P/L',
        'view-full-month': 'View Full Month Calendar',
        'month-details': 'Month Details',
        'close': 'Close',
        'weekly-summary': 'Weekly Summary',
        'selected-week': 'Selected Week',
        'week-trades': 'Week Trades',
        'week-win-rate': 'Week Win Rate',
        'week-best-day': 'Best Day',
        'week-worst-day': 'Worst Day',
        'week-trade-details': 'Week Trade Details',
        'cost-basis': 'Cost Basis',
        'trade-count': 'Trades',
        'delete-selected': 'Delete Selected',
        'daily-input': 'Daily Input',
        'metrics-dashboard': 'Metrics Dashboard',
        'bias-analysis': 'Bias Analysis',
        'pattern-insights': 'Pattern Insights',
        'daily-data-input': 'Daily Data Input',
        'biological-data': 'Biological Data',
        'screen-time': 'Screen Time Before Trading (hours)',
        'planned-start': 'Planned Start Time',
        'actual-start': 'Actual Start Time',
        'environment-type': 'Environment Type',
        'distractions': 'Distractions Count',
        'financial-pressure': 'Financial Pressure Level (1-5)',
        'predictions': 'Pre-Market Predictions',
        'predicted-win-rate': 'Predicted Win Rate (%)',
        'planned-trades': 'Planned Trades Count',
        'planned-position-size': 'Planned Avg Position Size ($)',
        'calculate-score': 'Calculate Daily Score',
        'psychology-dashboard': 'Psychology Dashboard',
        'daily-psychology-score': 'Daily Psychology Score',
        'discipline-factor': 'Discipline Factor',
        'consistency-factor': 'Consistency Factor',
        'total-score': 'Total Score',
        'weekly-bias-risk': 'Weekly Bias Risk Assessment',
        'overconfidence-risk': 'Overconfidence Risk',
        'loss-aversion-risk': 'Loss Aversion Risk',
        'anchoring-risk': 'Anchoring Risk',
        'performance-correlation': 'Performance Correlation Analysis',
        'sleep-performance': 'Sleep vs Performance',
        'caffeine-performance': 'Caffeine vs Performance',
        'timing-performance': 'Timing vs Performance',
        'confidence-performance': 'Confidence vs Performance',
        'bias-analysis-title': 'Quantified Bias Analysis',
        'overconfidence-bias': 'Overconfidence Bias',
        'loss-aversion-bias': 'Loss Aversion Bias',
        'anchoring-bias': 'Anchoring Bias',
        'calibration-error': 'Calibration Error',
        'overtrading-index': 'Overtrading Index',
        'position-deviation': 'Position Size Deviation',
        'disposition-ratio': 'Disposition Ratio',
        'stop-loss-execution': 'Stop Loss Execution Rate',
        'stop-loss-modification': 'Stop Loss Modification Rate',
        'entry-price-dependency': 'Entry Price Dependency',
        'round-number-bias': 'Round Number Bias',
        'recent-high-anchor': 'Recent High Anchor',
        'weekly-risk-summary': 'Weekly Risk Summary',
        'overall-bias-risk': 'Overall Bias Risk',
        'risk-trend': 'Risk Trend',
        'action-needed': 'Action Needed',
        'end-time': 'End Time',
        'environment-score': 'Environment Score',
        'risk-assessment': 'Risk Assessment',
        'time-based-performance': 'Time-Based Performance Analysis',
        'optimal-sleep-range': 'Optimal Sleep Range',
        'delay-impact': 'Start Delay Impact',
        'consecutive-pattern': 'Consecutive Trades Pattern',
        'after-losses': 'Performance After Losses',
        'after-wins': 'Performance After Wins',
        'ai-insights': 'AI-Generated Insights',
        'no-insights': 'Collect more psychology data to generate personalized insights.',
        'psychology-performance-chart': 'Psychology vs Performance Analysis',
        'pattern-insights-title': 'Pattern Insights & Recommendations',
        'worst-trading-hour': 'Worst Trading Hour',
        'after-1-loss': 'After 1 loss',
        'after-2-losses': 'After 2 losses',
        'after-3-losses': 'After 3+ losses',
        'after-1-win': 'After 1 win',
        'after-2-wins': 'After 2 wins',
        'after-3-wins': 'After 3+ wins',
        'win-rate-label': 'Win Rate'
    },
    ko: {
        'dashboard': '대시보드',
        'calendar': '캘린더 뷰',
        'analytics': '분석',
        'notes': '노트',
        'tradelist': '거래 목록',
        'settings': '설정',
        'dashboard-title': '트레이딩 대시보드',
        'dashboard-subtitle': '거래와 성과를 추적하세요',
        'language': '언어:',
        'total-pl': '총 손익',
        'net-result': '순 결과',
        'trades': '거래',
        'total-count': '총 개수',
        'win-rate': '승률',
        'record-trade': '거래 기록',
        'symbol': '심볼',
        'shares': '주식수',
        'buy-price': '매수 가격',
        'sell-price': '매도 가격',
        'return-pct': '수익률 %',
        'pnl': '손익',
        'entry-time': '진입 시간',
        'exit-time': '청산 시간',
        'holding-time': '보유 시간',
        'edit': '편집',
        'auto': '자동',
        'reset': '초기화',
        'add-trade': '거래 추가',
        'performance': '성과',
        'best-trade': '최고 거래',
        'worst-trade': '최악 거래',
        'avg-win': '평균 수익',
        'avg-loss': '평균 손실',
        'total-invested': '총 투자금',
        'profit-factor': '수익 팩터',
        'trade-history': '거래 내역',
        'date': '날짜',
        'time': '시간',
        'actions': '작업',
        'no-trades': '아직 기록된 거래가 없습니다',
        'calendar-title': '캘린더 뷰',
        'calendar-subtitle': '시간에 따른 거래 성과를 시각화하세요',
        'clear-selection': '선택 해제',
        'calendar-help': '캘린더에서 클릭 및 드래그로 날짜 범위를 선택하거나, 하루를 클릭하여 세부정보를 확인하세요.',
        'selected-period': '선택된 기간',
        'total-trades': '총 거래',
        'avg-daily-pl': '일일 평균 손익',
        'best-day': '최고의 날',
        'worst-day': '최악의 날',
        'weekly-pl': '주간 손익',
        'analytics-title': '트레이딩 분석',
        'notes-title': '트레이딩 노트',
        'notes-subtitle': '트레이딩 인사이트와 생각을 기록하세요',
        'new-note': '새 노트',
        'note-title-placeholder': '노트 제목을 입력하세요...',
        'note-content-placeholder': '여기에 노트를 작성하세요...',
        'cancel': '취소',
        'save-note': '노트 저장',
        'no-notes': '아직 작성된 노트가 없습니다. "새 노트"를 클릭하여 시작하세요.',
        'daily-review': '일일 리뷰',
        'strategy': '전략',
        'general': '일반',
        'no-daily-notes': '일일 리뷰 노트가 아직 없습니다. "새 노트"를 클릭하여 시작하세요.',
        'no-strategy-notes': '전략 노트가 아직 없습니다. "새 노트"를 클릭하여 시작하세요.',
        'no-general-notes': '일반 노트가 아직 없습니다. "새 노트"를 클릭하여 시작하세요.',
        'tradelist-title': '거래 목록',
        'tradelist-subtitle': '모든 거래의 완전한 목록',
        'settings-title': '설정',
        'settings-subtitle': '거래 저널 설정을 구성하세요',
        'general-settings': '일반 설정',
        'default-language': '기본 언어',
        'data-management': '데이터 관리',
        'export-data': '데이터 내보내기',
        'import-data': '데이터 가져오기',
        'danger-zone': '위험 구역',
        'clear-all-data': '모든 데이터 삭제',
        'all-time': '전체 기간',
        'this-month': '이번 달',
        'this-week': '이번 주',
        'today': '오늘',
        'detail': '상세',
        'charts': '차트',
        'net-profit': '순이익',
        'largest-win': '최대 수익',
        'largest-loss': '최대 손실',
        'performance-summary': '성과 요약',
        'trading-performance': '거래 성과',
        'total-gain': '총 수익',
        'total-loss': '총 손실',
        'total-fees': '총 수수료',
        'total-volume': '총 거래량',
        'win-loss-stats': '승패 통계',
        'winning-trades': '수익 거래',
        'losing-trades': '손실 거래',
        'avg-winning-trade': '평균 수익 거래',
        'avg-losing-trade': '평균 손실 거래',
        'daily-performance': '일일 성과',
        'daily-per-win': '승리당 일일 손익',
        'daily-per-loss': '패배당 일일 손익',
        'daily-per-fees': '일당 수수료',
        'best-trading-day': '최고 거래일',
        'worst-trading-day': '최악 거래일',
        'time-analysis': '시간 분석',
        'avg-hold-time': '평균 보유시간',
        'shortest-hold': '최단 보유',
        'longest-hold': '최장 보유',
        'best-trading-hour': '최고 거래시간',
        'worst-trading-hour': '최악 거래시간',
        'best-day-week': '최고 요일',
        'trading-activity': '거래 활동',
        'trading-days': '거래일수',
        'avg-trades-per-day': '일평균 거래수',
        'max-trades-day': '일최대 거래수',
        'avg-position-size': '평균 포지션 크기',
        'largest-position': '최대 포지션',
        'smallest-position': '최소 포지션',
        'streak-analysis': '연속성 분석',
        'current-streak': '현재 연속',
        'max-win-streak': '최대 연승',
        'max-loss-streak': '최대 연패',
        'current-win-streak': '현재 연승',
        'current-loss-streak': '현재 연패',
        'avg-win-streak': '평균 연승',
        'symbol-performance': '심볼별 성과',
        'most-profitable-symbol': '최고 수익 심볼',
        'least-profitable-symbol': '최저 수익 심볼',
        'most-traded-symbol': '최다 거래 심볼',
        'unique-symbols': '고유 심볼수',
        'symbol-win-rate': '최고 심볼 승률',
        'symbol-avg-return': '최고 심볼 평균수익',
        'risk-management': '리스크 관리',
        'max-drawdown': '최대 드로다운',
        'current-drawdown': '현재 드로다운',
        'recovery-factor': '회복 팩터',
        'max-daily-loss': '최대 일손실',
        'max-daily-gain': '최대 일수익',
        'risk-reward-ratio': '평균 위험/보상',
        'daily-fees': '일일 수수료',
        'basic-charts': '기본 성과 차트',
        'cumulative-pl': '누적 손익',
        'win-loss-ratio': '승패 분포',
        'daily-pl': '일일 손익',
        'monthly-performance': '월별 성과',
        'equity-curve': '자산 곡선',
        'drawdown-chart': '드로다운 분석',
        'symbol-performance-chart': '심볼 성과',
        'time-distribution': '시간 분포',
        'return-distribution': '수익률 분포',
        'rolling-performance': '롤링 성과',
        'volume-analysis': '거래량 분석',
        'correlation-matrix': '성과 상관관계',
        'volatility-analysis': '변동성 분석',
        'risk-return-scatter': '위험-수익 산점도',
        'performance-attribution': '성과 요인분석',
        'trade-duration-analysis': '거래 기간 분석',
        'pl-heatmap': '손익 히트맵',
        'win-rate-by-time': '시간별 승률',
        'position-sizing-analysis': '포지션 크기 분석',
        'trading-efficiency-metrics': '거래 효율성 지표',
        'all-notes': '전체',
        'back': '뒤로',
        'show-more': '더보기',
        'show-less': '접기',
        'position-calculator': '포지션 계산기',
        'kelly-criterion-calculator': '켈리 기준 계산기',
        'account-balance': '계좌 잔고 ($)',
        'win-rate-input': '승률 (%)',
        'average-win': '평균 수익 ($)',
        'average-loss': '평균 손실 ($)',
        'auto-load-trade-data': '거래 이력에서 자동 계산',
        'kelly-percentage': '켈리 비율',
        'full-kelly-position': '풀 켈리 포지션',
        'quarter-kelly': '1/4 켈리 (25%)',
        'tenth-kelly': '1/10 켈리 (10%)',
        'ultra-safe': '매우 안전',
        'conservative': '보수적',
        'moderate': '보통',
        'position-analysis': '포지션 분석',
        'recommended-size': '권장 규모',
        'account-utilization': '계좌 활용률',
        'expected-value': '기댓값',
        'auto-analysis': '자동 분석',
        'recent-win-rate': '최근 승률',
        'pl-ratio': '손익 비율',
        'kelly-status': '켈리 상태',
        'safe': '안전',
        'medium': '보통',
        'high': '위험',
        'kelly-calculator': '켈리 계산기',
        'risk-calculator': '리스크 계산기',
        'risk-percentage': '리스크 비율 (%)',
        'entry-price': '진입 가격 ($)',
        'stop-loss-price': '손절 가격 ($)',
        'position-size': '포지션 크기',
        'shares-quantity': '주식 수량',
        'risk-per-share': '주당 리스크',
        'max-loss': '최대 손실',
        'breakeven-move': '손익분기 변동',
        'risk-amount': '리스크 금액',
        'kelly-strategies': '포지션 사이징 전략',
        'risk-analysis': '리스크 분석',
        'position-cost': '포지션 비용',
        'risk-ratio': '리스크 비율',
        'stop-distance': '손절 거리',
        'risk-management-calculator': '리스크 관리 계산기',
        'risk-presets': '리스크 비율',
        'trading-record': '거래 기록',
        'amount': '금액 ($)',
        'psychology': '심리',
        'psychology-title': '트레이딩 심리',
        'psychology-subtitle': '거래 심리를 분석하고 최적화하세요',
        'daily-psychology-input': '일일 심리 입력',
        'biological-rhythm': '생체 리듬',
        'sleep-hours': '수면 시간',
        'sleep-quality': '수면 질',
        'caffeine-intake': '카페인 섭취량 (mg)',
        'energy-level': '에너지 수준',
        'time-environment': '시간 및 환경',
        'planned-start-time': '계획된 시작 시간',
        'actual-start-time': '실제 시작 시간',
        'market-delay': '시장 개장 후 지연 (분)',
        'trading-environment': '거래 환경',
        'economic-pressure': '경제적 압박',
        'account-balance-psych': '계좌 잔고 ($)',
        'pressure-level': '재정적 압박 수준',
        'daily-target': '일일 손익 목표 ($)',
        'max-daily-loss': '최대 일일 손실 한도 ($)',
        'emotional-state': '감정 상태',
        'pre-market-mood': '장 전 기분',
        'confidence-level': '자신감 수준',
        'stress-level': '스트레스 수준',
        'focus-level': '집중력 수준',
        'save-psychology-data': '심리 데이터 저장',
        'psychology-metrics': '심리 지표',
        'daily-psych-score': '일일 심리 점수',
        'sleep-factor': '수면 요인',
        'stress-factor': '스트레스 요인',
        'environment-factor': '환경 요인',
        'pressure-index': '압박 지수',
        'emotional-readiness': '감정적 준비도',
        'psychology-insights': '심리 인사이트 및 권장사항',
        'no-psychology-data': '심리 데이터가 없습니다. 오늘의 데이터를 입력하여 인사이트를 받아보세요.',
        'start-time': '시작 시간',
        'reset-psychology-data': '데이터 초기화',
        'psychology-analysis': '심리 분석',
        'annual-trading-overview': '연간 거래 개요',
        'week-pnl': '주간 손익',
        'view-full-month': '전체 월 캘린더 보기',
        'month-details': '월별 상세',
        'close': '닫기',
        'weekly-summary': '주간 요약',
        'selected-week': '선택된 주',
        'week-trades': '주간 거래',
        'week-win-rate': '주간 승률',
        'week-best-day': '최고의 날',
        'week-worst-day': '최악의 날',
        'week-trade-details': '주간 거래 세부사항',
        'cost-basis': '평균단가',
        'trade-count': '거래',
        'delete-selected': '선택된 거래 삭제',
        'daily-input': '일일 입력',
        'metrics-dashboard': '지표 대시보드',
        'bias-analysis': '편향 분석',
        'pattern-insights': '패턴 인사이트',
        'daily-data-input': '일일 데이터 입력',
        'biological-data': '생체 데이터',
        'screen-time': '거래 전 스크린 타임 (시간)',
        'planned-start': '계획된 시작 시간',
        'actual-start': '실제 시작 시간',
        'environment-type': '환경 유형',
        'distractions': '방해 요소 횟수',
        'financial-pressure': '재정적 압박 수준 (1-5)',
        'predictions': '장전 예측',
        'predicted-win-rate': '예상 승률 (%)',
        'planned-trades': '계획된 거래 수',
        'planned-position-size': '계획된 평균 포지션 크기 ($)',
        'calculate-score': '일일 점수 계산',
        'psychology-dashboard': '심리 대시보드',
        'daily-psychology-score': '일일 심리 점수',
        'discipline-factor': '규율 요인',
        'consistency-factor': '일관성 요인',
        'total-score': '총점',
        'weekly-bias-risk': '주간 편향 위험 평가',
        'overconfidence-risk': '과신 위험',
        'loss-aversion-risk': '손실 회피 위험',
        'anchoring-risk': '앵커링 위험',
        'performance-correlation': '성과 상관관계 분석',
        'sleep-performance': '수면 vs 성과',
        'caffeine-performance': '카페인 vs 성과',
        'timing-performance': '타이밍 vs 성과',
        'confidence-performance': '자신감 vs 성과',
        'bias-analysis-title': '정량화된 편향 분석',
        'overconfidence-bias': '과신 편향',
        'loss-aversion-bias': '손실 회피 편향',
        'anchoring-bias': '앵커링 편향',
        'calibration-error': '캘리브레이션 오차',
        'overtrading-index': '과도거래 지수',
        'position-deviation': '포지션 크기 편차',
        'disposition-ratio': '처분 효과 비율',
        'stop-loss-execution': '손절매 실행률',
        'stop-loss-modification': '손절매 수정률',
        'entry-price-dependency': '진입가 의존도',
        'round-number-bias': '라운드 넘버 편향',
        'recent-high-anchor': '최근 고점 앵커',
        'weekly-risk-summary': '주간 위험 요약',
        'overall-bias-risk': '전체 편향 위험',
        'risk-trend': '위험 추세',
        'action-needed': '필요한 조치',
        'end-time': '종료 시간',
        'environment-score': '환경 점수',
        'risk-assessment': '위험 평가',
        'time-based-performance': '시간대별 성과 분석',
        'optimal-sleep-range': '최적 수면 범위',
        'delay-impact': '시작 지연 영향',
        'consecutive-pattern': '연속 거래 패턴',
        'after-losses': '손실 후 성과',
        'after-wins': '수익 후 성과',
        'ai-insights': 'AI 인사이트',
        'no-insights': '더 많은 심리 데이터와 거래 기록을 수집하여 개인화된 인사이트를 생성하세요.',
        'psychology-performance-chart': '심리 vs 성과 분석',
        'pattern-insights-title': '패턴 인사이트 및 권장사항',
        'worst-trading-hour': '최악 거래시간',
        'after-1-loss': '1회 손실 후',
        'after-2-losses': '2회 손실 후',
        'after-3-losses': '3회 이상 손실 후',
        'after-1-win': '1회 수익 후',
        'after-2-wins': '2회 수익 후',
        'after-3-wins': '3회 이상 수익 후',
        'win-rate-label': '승률'
    }
};

// ============================================
// Export for module usage (if needed)
// ============================================

if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        // State variables
        trades,
        notes,
        dailyFees,
        currentTradingDate,
        calendarDate,
        calendarStartDate,
        calendarEndDate,
        isSelecting,
        timeEditMode,
        selectedCalendarDay,
        currentLanguage,
        analyticsPeriod,
        dashboardStartDate,
        dashboardEndDate,
        analyticsStartDate,
        analyticsEndDate,
        tradesStartDate,
        tradesEndDate,
        currentAnalyticsSection,
        editingNoteId,
        currentNotesSection,
        currentViewingNoteId,
        currentTextColor,
        currentFont,
        psychologyData,
        currentPsychologySection,
        selectedWeekPnl,
        selectedTradesList,
        selectedTrades,
        currentDashboardSection,
        selectedKellyMultiplier,
        selectedMonthYear,
        selectedMonth,
        basicCharts,
        advancedCharts,
        
        // Translations
        translations
    };
}
