// ============================================
// Configuration & Global Variables
// ============================================

// Application State - Trading
let trades = [];
let notes = [];
let dailyFees = {};

// Date Management
let currentTradingDate = null; 
let calendarDate = new Date();
let calendarStartDate = null;
let calendarEndDate = null;
let selectedCalendarDay = null;
// UI State
let isSelecting = false;
let timeEditMode = false;
let currentLanguage = 'en';

// Analytics State
let analyticsPeriod = 'all';
let dashboardStartDate = null;
let dashboardEndDate = null;
let analyticsStartDate = null;
let analyticsEndDate = null;
let tradesStartDate = null;
let tradesEndDate = null;
let currentAnalyticsSection = 'detail';
let analyticsLoadedOnce = false;
let analyticsFilterState = null;
let marketDataLoadedOnce = false;
let marketDataFilterState = null;

// Notes State
let editingNoteId = null;
let currentNotesSection = 'all';
let currentViewingNoteId = null;
let currentTextColor = '#e4e4e7';
let currentFont = "'Inter', sans-serif";

// Psychology State
let psychologyData = {};
let currentPsychologySection = 'input';
let currentPsychologyDate = null;

// Principles State
let principlesData = {};
let currentPrinciplesDate = null;

// Calendar State
let selectedWeekPnl = null;
let selectedMonthYear = null;
let selectedMonth = null;

// Trade Selection State
let selectedTradesList = new Set();
let selectedTrades = new Set();

// Dashboard State
let currentDashboardSection = 'trading';
let selectedKellyMultiplier = 0.1;

// Chart instances
let basicCharts = {};
let advancedCharts = {};

// Window-level chart instance for psychology
if (typeof window !== 'undefined') {
    window.psychologyChart = null;
}

// Market Data State
let marketDataEnabled = true;
let loadingMarketData = false;
let marketDataQuotes = {};

// ============================================
// Language Translations
// ============================================

const translations = {
    en: {
        'dashboard': 'Dashboard',
        'calendar': 'Calendar View',
        'analytics': 'Analytics',
        'notes': 'Notes',
        'tradelist': 'Trade List',
        'settings': 'Settings',
        'dashboard-title': 'Trading Dashboard',
        'dashboard-subtitle': 'Track your trades and performance',
        'language': 'Language:',
        'total-pl': 'Total P/L',
        'net-result': 'Net Result',
        'trades': 'Trades',
        'total-count': 'Total Count',
        'win-rate': 'Win Rate',
        'record-trade': 'Record Trade',
        'symbol': 'Symbol',
        'shares': 'Shares',
        'buy-price': 'Buy Price',
        'sell-price': 'Sell Price',
        'return-pct': 'Return %',
        'pnl': 'P&L',
        'entry-time': 'Entry Time',
        'exit-time': 'Exit Time',
        'holding-time': 'Holding Time',
        'edit': 'Edit',
        'auto': 'Auto',
        'reset': 'Reset',
        'add-trade': 'Add Trade',
        'performance': 'Performance',
        'best-trade': 'Best Trade',
        'worst-trade': 'Worst Trade',
        'avg-win': 'Avg Win',
        'avg-loss': 'Avg Loss',
        'total-invested': 'Total Invested',
        'profit-factor': 'Profit Factor',
        'trade-history': 'Trade History',
        'date': 'Date',
        'time': 'Time',
        'actions': 'Actions',
        'no-trades': 'No trades recorded yet',
        'calendar-title': 'Calendar View',
        'calendar-subtitle': 'Visualize your trading performance over time',
        'clear-selection': 'Clear Selection',
        'calendar-help': 'Click and drag on calendar to select date range, or click on a day to see details',
        'selected-period': 'Selected Period',
        'total-trades': 'Total Trades',
        'avg-daily-pl': 'Avg Daily P/L',
        'best-day': 'Best Day',
        'worst-day': 'Worst Day',
        'weekly-pl': 'Weekly P/L',
        'analytics-title': 'Trading Analytics',
        'notes-title': 'Trading Notes',
        'notes-subtitle': 'Document your trading insights and thoughts',
        'new-note': 'New Note',
        'note-title-placeholder': 'Enter note title...',
        'note-content-placeholder': 'Write your note here...',
        'cancel': 'Cancel',
        'save-note': 'Save Note',
        'no-notes': 'No notes written yet. Click "New Note" to start.',
        'daily-review': 'Daily Review',
        'strategy': 'Strategy',
        'general': 'General',
        'no-daily-notes': 'No daily review notes yet. Click "New Note" to start.',
        'no-strategy-notes': 'No strategy notes yet. Click "New Note" to start.',
        'no-general-notes': 'No general notes yet. Click "New Note" to start.',
        'tradelist-title': 'Trade List',
        'tradelist-subtitle': 'Complete list of all your trades',
        'settings-title': 'Settings',
        'settings-subtitle': 'Configure your trading journal preferences',
        'general-settings': 'General Settings',
        'default-language': 'Default Language',
        'data-management': 'Data Management',
        'export-data': 'Export Data',
        'import-data': 'Import Data',
        'import-broker-data': 'Import Broker Data',
        'import-broker-description': 'Upload trade history from your broker (CSV or JSON format)',
        'import-broker-button': '📥 Import Broker CSV/JSON',
        'import-preview-title': 'Import Preview',
        'confirm-import': '✓ Confirm Import',
        'danger-zone': 'Danger Zone',
        'clear-all-data': 'Clear All Data',
        'all-time': 'All Time',
        'this-month': 'This Month',
        'this-week': 'This Week',
        'today': 'Today',
        'detail': 'Detail',
        'charts': 'Charts',
        'net-profit': 'Net Profit',
        'largest-win': 'Largest Win',
        'largest-loss': 'Largest Loss',
        'performance-summary': 'Performance Summary',
        'trading-performance': 'Trading Performance',
        'total-gain': 'Total Gain',
        'total-loss': 'Total Loss',
        'total-fees': 'Total Fees',
        'total-volume': 'Total Volume',
        'win-loss-stats': 'Win/Loss Statistics',
        'winning-trades': 'Winning Trades',
        'losing-trades': 'Losing Trades',
        'avg-winning-trade': 'Avg Winning Trade',
        'avg-losing-trade': 'Avg Losing Trade',
        'daily-performance': 'Daily Performance',
        'daily-per-win': 'Daily P&L per Win',
        'daily-per-loss': 'Daily P&L per Loss',
        'daily-per-fees': 'Daily Fees per Day',
        'best-trading-day': 'Best Trading Day',
        'worst-trading-day': 'Worst Trading Day',
        'time-analysis': 'Time Analysis',
        'avg-hold-time': 'Avg Hold Time',
        'shortest-hold': 'Shortest Hold',
        'longest-hold': 'Longest Hold',
        'best-trading-hour': 'Best Trading Hour',
        'worst-trading-hour': 'Worst Trading Hour',
        'best-day-week': 'Best Day of Week',
        'trading-activity': 'Trading Activity',
        'trading-days': 'Trading Days',
        'avg-trades-per-day': 'Avg Trades per Day',
        'max-trades-day': 'Max Trades in Day',
        'avg-position-size': 'Avg Position Size',
        'largest-position': 'Largest Position',
        'smallest-position': 'Smallest Position',
        'streak-analysis': 'Streak Analysis',
        'current-streak': 'Current Streak',
        'max-win-streak': 'Max Win Streak',
        'max-loss-streak': 'Max Loss Streak',
        'current-win-streak': 'Current Win Streak',
        'current-loss-streak': 'Current Loss Streak',
        'avg-win-streak': 'Avg Win Streak',
        'symbol-performance': 'Symbol Performance',
        'most-profitable-symbol': 'Most Profitable',
        'least-profitable-symbol': 'Least Profitable',
        'most-traded-symbol': 'Most Traded',
        'unique-symbols': 'Unique Symbols',
        'symbol-win-rate': 'Best Symbol Win Rate',
        'symbol-avg-return': 'Best Symbol Avg Return',
        'risk-management': 'Risk Management',
        'max-drawdown': 'Max Drawdown',
        'current-drawdown': 'Current Drawdown',
        'recovery-factor': 'Recovery Factor',
        'max-daily-loss': 'Max Daily Loss',
        'max-daily-gain': 'Max Daily Gain',
        'risk-reward-ratio': 'Avg Risk/Reward',
        'daily-fees': 'Daily Fees',
        'basic-charts': 'Basic Performance Charts',
        'cumulative-pl': 'Cumulative P&L',
        'win-loss-ratio': 'Win/Loss Distribution',
        'daily-pl': 'Daily P&L',
        'monthly-performance': 'Monthly Performance',
        'equity-curve': 'Equity Curve',
        'drawdown-chart': 'Drawdown Analysis',
        'symbol-performance-chart': 'Symbol Performance',
        'time-distribution': 'Time Distribution',
        'return-distribution': 'Return Distribution',
        'rolling-performance': 'Rolling Performance',
        'volume-analysis': 'Volume Analysis',
        'correlation-matrix': 'Performance Correlation',
        'volatility-analysis': 'Volatility Analysis',
        'risk-return-scatter': 'Risk-Return Scatter',
        'performance-attribution': 'Performance Attribution',
        'trade-duration-analysis': 'Trade Duration Analysis',
        'pl-heatmap': 'P&L Heatmap',
        'win-rate-by-time': 'Win Rate by Time',
        'position-sizing-analysis': 'Position Sizing Analysis',
        'trading-efficiency-metrics': 'Trading Efficiency Metrics',
        'all-notes': 'All',
        'back': 'Back',
        'show-more': 'Show more',
        'show-less': 'Show less',
        'position-calculator': 'Position Calculator',
        'kelly-criterion-calculator': 'Kelly Criterion Calculator',
        'account-balance': 'Account Balance ($)',
        'win-rate-input': 'Win Rate (%)',
        'average-win': 'Average Win ($)',
        'average-loss': 'Average Loss ($)',
        'auto-load-trade-data': 'Auto Load from Trade History',
        'kelly-percentage': 'Kelly Percentage',
        'full-kelly-position': 'Full Kelly Position',
        'quarter-kelly': 'Quarter Kelly (25%)',
        'tenth-kelly': 'Tenth Kelly (10%)',
        'ultra-safe': 'Ultra Safe',
        'conservative': 'Conservative',
        'moderate': 'Moderate',
        'position-analysis': 'Position Analysis',
        'recommended-size': 'Recommended Size',
        'account-utilization': 'Account Utilization',
        'expected-value': 'Expected Value',
        'auto-analysis': 'Auto Analysis',
        'recent-win-rate': 'Recent Win Rate',
        'pl-ratio': 'P&L Ratio',
        'kelly-status': 'Kelly Status',
        'safe': 'Safe',
        'medium': 'Medium',
        'high': 'High',
        'kelly-calculator': 'Kelly Calculator',
        'risk-calculator': 'Risk Calculator',
        'risk-percentage': 'Risk Percentage (%)',
        'entry-price': 'Entry Price ($)',
        'stop-loss-price': 'Stop Loss Price ($)',
        'position-size': 'Position Size',
        'shares-quantity': 'Shares Quantity',
        'risk-per-share': 'Risk per Share',
        'max-loss': 'Max Loss',
        'breakeven-move': 'Breakeven Move',
        'risk-amount': 'Risk Amount',
        'kelly-strategies': 'Position Sizing Strategies',
        'risk-analysis': 'Risk Analysis',
        'position-cost': 'Position Cost',
        'risk-ratio': 'Risk Ratio',
        'stop-distance': 'Stop Distance',
        'risk-management-calculator': 'Risk Management Calculator',
        'risk-presets': 'Risk Ratio',
        'trading-record': 'Trading Record',
        'amount': 'Amount ($)',
        'principles': 'Principles',
        'principles-title': 'Trading Principles',
        'principles-subtitle': 'Define and track your trading rules',
        'save-principles-data': 'Save Principles Data',
        'reset-principles-data': 'Reset Data',
        'account-rules': 'Account Rules',
        'trade-details': 'Trade Details',
        'consecutive-loss-limit': 'Consecutive Loss Limit',
        'max-single-loss': 'Max Single Loss ($)',
        'max-position-size': 'Max Position Size ($)',
        'min-risk-reward': 'Min Risk/Reward Ratio',
        'warning-triggers': 'Warning Triggers',
        'warning-triggers-subtitle': 'Track rule violations and warnings',
        'consecutive-loss-warning': 'Consecutive Loss',
        'single-loss-warning': 'Single Loss Exceed',
        'position-size-warning': 'Position Size Exceed',
        'risk-reward-warning': 'Risk/Reward Below Min',
        'daily-target-warning': 'Daily Target Hit',
        'max-loss-warning': 'Max Daily Loss Hit',
        'trade-count-warning': 'Trade Count Limit Hit',
        'times-triggered': 'times',
        'no-warnings': 'No warnings today',
        'trade-details-score': 'Trade Details Score',
        'rules-compliance': 'Rules Compliance',
        'rules-violations': 'Rules Violations',
        'principles-warnings': 'Principles Warnings',
        'psychology': 'Psychology',
        'psychology-title': 'Trading Psychology',
        'psychology-subtitle': 'Analyze and optimize your trading psychology',
        'daily-psychology-input': 'Daily Psychology Input',
        'biological-rhythm': 'Biological Rhythm',
        'sleep-hours': 'Sleep Hours',
        'sleep-quality': 'Sleep Quality',
        'caffeine-intake': 'Caffeine Intake (mg)',
        'energy-level': 'Energy Level',
        'time-environment': 'Time & Environment',
        'planned-start-time': 'Planned Start Time',
        'actual-start-time': 'Actual Start Time',
        'market-delay': 'Market Open Delay (min)',
        'trading-environment': 'Trading Environment',
        'economic-pressure': 'Economic Pressure',
        'account-balance-psych': 'Account Balance ($)',
        'pressure-level': 'Financial Pressure Level',
        'daily-target': 'Daily P&L Target ($)',
        'max-daily-loss': 'Max Daily Loss Limit ($)',
        'max-trade-count': 'Trade Count Limit',
        'emotional-state': 'Emotional State',
        'pre-market-mood': 'Pre-Market Mood',
        'confidence-level': 'Confidence Level',
        'stress-level': 'Stress Level',
        'focus-level': 'Focus Level',
        'save-psychology-data': 'Save Psychology Data',
        'psychology-metrics': 'Psychology Metrics',
        'daily-psych-score': 'Daily Psychology Score',
        'sleep-factor': 'Sleep Factor',
        'stress-factor': 'Stress Factor',
        'environment-factor': 'Environment Factor',
        'pressure-index': 'Pressure Index',
        'emotional-readiness': 'Emotional Readiness',
        'psychology-insights': 'Psychology Insights & Recommendations',
        'no-psychology-data': 'No psychology data available. Fill in today\'s data to get insights.',
        'start-time': 'Start Time',
        'reset-psychology-data': 'Reset Data',
        'psychology-analysis': 'Psychology Analysis',
        'annual-trading-overview': 'Annual Trading Overview',
        'week-pnl': 'Week P/L',
        'view-full-month': 'View Full Month Calendar',
        'month-details': 'Month Details',
        'close': 'Close',
        'weekly-summary': 'Weekly Summary',
        'selected-week': 'Selected Week',
        'week-trades': 'Week Trades',
        'week-win-rate': 'Week Win Rate',
        'week-best-day': 'Best Day',
        'week-worst-day': 'Worst Day',
        'week-trade-details': 'Week Trade Details',
        'cost-basis': 'Cost Basis',
        'trade-count': 'Trades',
        'delete-selected': 'Delete Selected',
        'daily-input': 'Daily Input',
        'metrics-dashboard': 'Metrics Dashboard',
        'bias-analysis': 'Bias Analysis',
        'algorithmic-analysis': 'Algorithmic Analysis',
        'daily-data-input': 'Daily Data Input',
        'biological-data': 'Biological Data',
        'screen-time': 'Screen Time Before Trading (hours)',
        'planned-start': 'Planned Start Time',
        'actual-start': 'Actual Start Time',
        'environment-type': 'Environment Type',
        'distractions': 'Distractions Count',
        'financial-pressure': 'Financial Pressure Level (1-5)',
        'predictions': 'Pre-Market Predictions',
        'predicted-win-rate': 'Predicted Win Rate (%)',
        'planned-trades': 'Planned Trades Count',
        'planned-position-size': 'Planned Avg Position Size ($)',
        'calculate-score': 'Calculate Daily Score',
        'psychology-dashboard': 'Psychology Dashboard',
        'daily-psychology-score': 'Daily Psychology Score',
        'discipline-factor': 'Discipline Factor',
        'consistency-factor': 'Consistency Factor',
        'total-score': 'Total Score',
        'weekly-bias-risk': 'Weekly Bias Risk Assessment',
        'overconfidence-risk': 'Overconfidence Risk',
        'loss-aversion-risk': 'Loss Aversion Risk',
        'anchoring-risk': 'Anchoring Risk',
        'performance-correlation': 'Performance Correlation Analysis',
        'sleep-performance': 'Sleep vs Performance',
        'caffeine-performance': 'Caffeine vs Performance',
        'timing-performance': 'Timing vs Performance',
        'confidence-performance': 'Confidence vs Performance',
        'bias-analysis-title': 'Quantified Bias Analysis',
        'overconfidence-bias': 'Overconfidence Bias',
        'loss-aversion-bias': 'Loss Aversion Bias',
        'anchoring-bias': 'Anchoring Bias',
        'calibration-error': 'Calibration Error',
        'overtrading-index': 'Overtrading Index',
        'position-deviation': 'Position Size Deviation',
        'disposition-ratio': 'Disposition Ratio',
        'stop-loss-execution': 'Stop Loss Execution Rate',
        'stop-loss-modification': 'Stop Loss Modification Rate',
        'entry-price-dependency': 'Entry Price Dependency',
        'round-number-bias': 'Round Number Bias',
        'recent-high-anchor': 'Recent High Anchor',
        'weekly-risk-summary': 'Weekly Risk Summary',
        'overall-bias-risk': 'Overall Bias Risk',
        'risk-trend': 'Risk Trend',
        'action-needed': 'Action Needed',
        'end-time': 'End Time',
        'environment-score': 'Environment Score',
        'risk-assessment': 'Risk Assessment',
        'time-based-performance': 'Time-Based Performance Analysis',
        'optimal-sleep-range': 'Optimal Sleep Range',
        'delay-impact': 'Start Delay Impact',
        'consecutive-pattern': 'Consecutive Trades Pattern',
        'after-losses': 'Performance After Losses',
        'after-wins': 'Performance After Wins',
        'ai-insights': 'AI-Generated Insights',
        'no-insights': 'Collect more psychology data to generate personalized insights.',
        'psychology-performance-chart': 'Psychology vs Performance Analysis',
        'algorithmic-analysis-title': 'Algorithmic Analysis & Intelligence',
        'worst-trading-hour': 'Worst Trading Hour',
        'after-1-loss': 'After 1 loss',
        'after-2-losses': 'After 2 losses',
        'after-3-losses': 'After 3+ losses',
        'after-1-win': 'After 1 win',
        'after-2-wins': 'After 2 wins',
        'after-3-wins': 'After 3+ wins',
        'win-rate-label': 'Win Rate',
        'limit-warning-profit-title': 'Daily Target Achieved!',
        'limit-warning-profit-message': 'Congratulations! You have reached your daily profit target.',
        'limit-warning-loss-title': 'Daily Loss Limit Exceeded!',
        'limit-warning-loss-message': 'Warning! You have exceeded your maximum daily loss limit.',
        'limit-warning-tradecount-title': 'Trade Count Limit Exceeded!',
        'limit-warning-tradecount-message': 'You have exceeded your daily trade count limit. Consider taking a break.',
        'limit-warning-current': 'Current P/L',
        'limit-warning-target': 'Daily Target',
        'limit-warning-limit': 'Loss Limit',
        'limit-warning-current-count': 'Current Trades',
        'limit-warning-count-limit': 'Limit',
        'limit-warning-ok': 'OK, I Understand',
        'market-data': 'Market Data',
        'market-context': 'Market Context',
        'symbol-quotes': 'Symbol Quotes',
        'price-context': 'Price Context Analysis',
        'current-price': 'Current Price',
        'day-change': 'Day Change',
        'volume': 'Volume',
        'open': 'Open',
        'high': 'High',
        'low': 'Low',
        'previous-close': 'Prev Close',
        'last-updated': 'Last Updated',
        'refresh-quotes': 'Refresh Quotes',
        'loading-market-data': 'Loading market data...',
        'api-key-settings': 'API Key Settings',
        'alpha-vantage-api-key': 'Alpha Vantage API Key',
        'save-api-key': 'Save API Key',
        'clear-market-cache': 'Clear Market Data Cache',
        'entry-position': 'Entry Position',
        'exit-position': 'Exit Position',
        'vs-market-high': 'vs Market High',
        'vs-market-low': 'vs Market Low',
        'market-range': 'Market Range',
        'no-market-data': 'No market data available',
        'api-rate-limit': 'API rate limit reached. Please wait.',
        'market-characteristics': 'Market Characteristics',
        'avg-float-winners': 'Avg Float (Winners)',
        'avg-marketcap-winners': 'Avg Market Cap (Winners)',
        'avg-beta-winners': 'Avg Beta (Winners)',
        'symbols-analyzed': 'Symbols Analyzed',
        'volume-liquidity': 'Volume & Liquidity',
        'high-volume-winrate': 'High Volume Win Rate',
        'low-volume-winrate': 'Low Volume Win Rate',
        'median-volume': 'Median Volume',
        'volatility-performance': 'Volatility Performance',
        'high-volatility': 'High Volatility (Beta > 1.5)',
        'medium-volatility': 'Medium Volatility (1.0-1.5)',
        'low-volatility': 'Low Volatility (Beta < 1.0)',
        'volatility-winrate': 'Win Rate',
        'volatility-avgreturn': 'Avg Return',
        'marketcap-preference': 'Market Cap Preference',
        'small-cap': 'Small Cap (< $2B)',
        'mid-cap': 'Mid Cap ($2B - $10B)',
        'large-cap': 'Large Cap (> $10B)',
        'cap-winrate': 'Win Rate',
        'cap-avgpnl': 'Avg P/L',
        'cap-trades': 'Trades',
        'loading-market-analysis': 'Loading market analysis...',
        'no-market-analysis': 'Not enough market data for analysis',
        'million-shares': 'M shares',
        'billion-dollars': 'B',

        // New market analysis translations
        'intraday-performance': 'Intraday Performance',
        'intraday-20': 'Up 20%+ at Entry',
        'intraday-30': 'Up 30%+ at Entry',
        'intraday-50': 'Up 50%+ at Entry',
        'intraday-100': 'Up 100%+ at Entry',
        'sector-performance': 'Sector Performance',
        'sector': 'Sector',
        'spy-correlation': 'SPY Direction Correlation',
        'spy-up-days': 'SPY Up Days',
        'spy-down-days': 'SPY Down Days',
        'relative-volume': 'Relative Volume Correlation',
        'high-rel-vol': 'High Rel Vol (2.0x+)',
        'medium-rel-vol': 'Medium Rel Vol (1.5-2.0x)',
        'normal-rel-vol': 'Normal Rel Vol (<1.5x)',

        // Error messages
        'api-limit-reached': 'API Limit Reached',
        'data-unavailable': 'Data Unavailable',
        'no-api-key': 'API Key Not Set',
        'rate-limit-wait': 'Rate limit reached. Please wait...',

        // Advanced Analysis
        'entry-exit-timing': 'Entry/Exit Timing Quality',
        'avg-entry-position': 'Avg Entry Position',
        'avg-exit-position': 'Avg Exit Position',
        'timing-score': 'Timing Score',
        'early-entry-rate': 'Early Entry Rate',
        'profit-taking-rate': 'Profit Taking Rate',
        'of-range': 'of range',
        'gap-trading-performance': 'Gap Trading Performance',
        'gap-up-winrate': 'Gap Up Win Rate',
        'gap-down-winrate': 'Gap Down Win Rate',
        'large-gap-winrate': 'Large Gap (5%+) Win Rate',
        'best-gap-range': 'Best Gap Range',
        'sector-rotation': 'Sector Rotation Analysis',
        'top-sector': 'Top Performing Sector',
        'sector-winrate': 'Sector Win Rate',
        'sector-avg-return': 'Sector Avg Return',
        'sector-diversity': 'Sector Diversity',
        'price-level-psychology': 'Price Level Psychology',
        'under-5-winrate': 'Under $5 Win Rate',
        'range-5-20-winrate': '$5-$20 Win Rate',
        'over-20-winrate': 'Over $20 Win Rate',
        'optimal-price-range': 'Optimal Price Range',
        'atr-correlation': 'Volatility (ATR) Correlation',
        'high-vol-winrate': 'High Volatility Win Rate',
        'low-vol-winrate': 'Low Volatility Win Rate',
        'median-volatility': 'Median Volatility',
        'trades-analyzed': 'Trades Analyzed',

        // Algorithmic Analysis translations
        'multi-factor-attribution': 'Multi-Factor Performance Attribution',
        'feature-importance': 'Feature Importance Analysis',
        'psychological-state': 'Psychological State',
        'market-conditions': 'Market Conditions',
        'performance-trend': 'Recent Performance Trend',
        'bias-risk': 'Behavioral Bias Risk',
        'recommended-action': 'Recommended Action',
        'behavioral-patterns': 'Behavioral Pattern Recognition',
        'detected-patterns': 'Detected Patterns',
        'market-intelligence': 'Market Context Intelligence',
        'spy-correlation-analysis': 'SPY Correlation Analysis',
        'volatility-regime': 'Volatility Regime Analysis',
        'statistical-edge': 'Statistical Edge Analysis',
        'win-rate-significance': 'Win Rate Significance',
        'confidence-interval': 'Confidence Interval',
        'expected-value-per-trade': 'Expected Value per Trade',
        'kelly-optimal': 'Kelly Optimal Position',
        'sharpe-ratio': 'Sharpe Ratio',
        'statistical-significance': 'Statistical Significance',
        'adaptive-recommendations': 'Adaptive Strategy Recommendations',
        'high-priority': 'HIGH PRIORITY',
        'optimization': 'OPTIMIZATION',
        'risk-warning': 'RISK WARNING',
        'feature-impact': 'Impact',
        'sample-size': 'Sample',
        'current-score': 'Current Score',
        'excellent': 'Excellent',
        'good': 'Good',
        'neutral': 'Neutral',
        'elevated': 'Elevated',
        'critical': 'Critical',
        'highly-significant': 'Highly Significant',
        'significant': 'Significant',
        'not-significant': 'Not Significant',
        'regime-high-vol': 'High Volatility Regime',
        'regime-medium-vol': 'Medium Volatility Regime',
        'regime-low-vol': 'Low Volatility Regime',
        'regime-performance': 'Regime Performance',
        'current-regime': 'Current Regime',
        'best-regime': 'Best Performing Regime',
        'correlation-strength': 'Correlation Strength',
        'strong-positive': 'Strong Positive',
        'moderate-positive': 'Moderate Positive',
        'weak': 'Weak',
        'moderate-negative': 'Moderate Negative',
        'strong-negative': 'Strong Negative',
        'next-trade-probability': 'Next Trade Success Probability',
        'probability-based-on': 'Based on current conditions',
        'edge-detected': 'Statistical Edge Detected',
        'no-edge': 'No Statistical Edge',
        'quality-score': 'Trade Quality Score',
        'liquidity-score': 'Liquidity Score',
        'timing-quality': 'Timing Quality',
        'risk-management-quality': 'Risk Management Quality',

        // Hero Dashboard translations
        'ai-powered-badge': 'AI-POWERED',
        'trading-intelligence-center': 'Trading Intelligence Center',
        'hero-trade-quality': 'Trade Quality',
        'hero-current-score': 'Current Score',
        'hero-win-probability': 'Next Win Probability',
        'hero-recommendation': 'Recommendation',
        'hero-performance-forecast': 'Performance Forecast',
        'hero-expected-daily': 'Expected Daily P/L',
        'hero-analyze-now': 'Analyze Now',
        'hero-predict-session': 'Predict Session',
        'hero-export-report': 'Export Report',
        'favorable': 'FAVORABLE',
        'neutral-rec': 'NEUTRAL',
        'unfavorable': 'UNFAVORABLE',
        'confidence-high': 'High Confidence',
        'confidence-medium': 'Medium Confidence',
        'confidence-low': 'Low Confidence',
        'session-outlook': 'Session Outlook',
        'optimal-conditions': 'Optimal Conditions',
        'proceed-cautiously': 'Proceed Cautiously',
        'high-risk-session': 'High Risk Session',
        'bias-detected': 'Behavioral Bias Detected',
        'similar-patterns-found': 'Similar Historical Patterns Found',
        'optimal-position-sizing': 'Optimal Position Sizing',
        'monte-carlo-forecast': 'Monte Carlo Forecast',
        'expected-range': 'Expected Range',
        'best-case': 'Best Case',
        'worst-case': 'Worst Case',
        'pattern-match': 'Pattern Match',
        'historical-similarity': 'Historical Similarity',
        'recommended-symbols': 'Recommended Symbols',

        // Additional Hero Dashboard translations
        'hero-subtitle': 'Real-time algorithmic analysis powered by machine learning and behavioral pattern recognition',
        'quality-badge': 'QUALITY',
        'prediction-badge': 'PREDICTION',
        'forecast-badge': 'FORECAST',
        'hero-quality-label': 'Trade Quality Score',
        'hero-probability-label': 'Win Probability',
        'hero-forecast-label': 'Session Prediction',
        'confidence-label': 'Confidence:',
        'calculating-status': 'Calculating...',
        'trend-from-avg': 'from avg',
        'trend-vs-avg': 'vs avg',

        // Loading and status messages
        'loading-analysis': 'Loading feature importance analysis...',
        'calculating-risk': 'Calculating real-time risk assessment...',
        'analyzing-patterns': 'Analyzing trading patterns...',
        'analyzing-market': 'Analyzing market conditions...',
        'computing-stats': 'Computing statistical significance...',
        'generating-recs': 'Generating personalized recommendations...',
        'insufficient-data-multi': 'Insufficient data for multi-factor analysis. Need at least 10 trades with psychology data.',

        // New AI analysis module titles
        'temporal-pattern-recognition': 'Temporal Pattern Recognition',
        'trade-clustering-analysis': 'Trade Clustering Analysis',
        'correlation-matrix-analysis': 'Multivariate Correlation Analysis',
        'predictive-model': 'Predictive Performance Model',
        'optimization-engine': 'Optimization Recommendation Engine',

        // Correlation analysis
        'sleep-caffeine-interaction': 'Sleep-Caffeine Interaction',
        'stress-confidence-combo': 'Stress-Confidence Combination',
        'time-psychology-cross': 'Time-Psychology Cross Analysis',
        'environment-focus-correlation': 'Environment-Focus Correlation',
        'correlation-coefficient': 'Correlation Coefficient',
        'correlation-heatmap': 'Correlation Heatmap',

        // Temporal patterns
        'weekday-weekend-diff': 'Weekday vs Weekend Performance',
        'monthly-seasonality': 'Monthly Seasonality Pattern',
        'optimal-trading-days': 'Optimal Trading Days',
        'consecutive-day-fatigue': 'Consecutive Day Fatigue Analysis',
        'post-break-performance': 'Post-Break Performance',

        // Clustering
        'cluster-scalping': 'Quick Scalping (5-30 min)',
        'cluster-swing': 'Swing Trades (30-120 min)',
        'cluster-position': 'Position Trades (120+ min)',
        'cluster-performance': 'Cluster Performance',
        'optimal-cluster': 'Optimal Cluster',

        // Predictive model
        'win-prediction-model': 'Win/Loss Prediction Model',
        'feature-importance-rank': 'Feature Importance Ranking',
        'threshold-analysis': 'Threshold Analysis',
        'real-time-probability': 'Real-time Probability',
        'roc-curve': 'ROC Curve',
        'prediction-accuracy': 'Prediction Accuracy',

        // Optimization
        'optimal-position-size-rec': 'Optimal Position Size',
        'optimal-time-window': 'Optimal Time Window',
        'optimal-psychology-state': 'Optimal Psychology State',
        'what-if-scenario': 'What-If Scenario Analysis',
        'expected-profit-range': 'Expected Profit Range',
        'simulation-results': 'Simulation Results',

        // NEW: Advanced Risk Metrics
        'maximum-drawdown': 'Maximum Drawdown (MDD)',
        'sortino-ratio': 'Sortino Ratio',
        'kelly-percentage': 'Kelly Criterion %',
        'downside-deviation': 'Downside Deviation',
        'current-mdd': 'Current MDD',
        'mdd-tooltip': 'Maximum peak-to-trough decline in capital. Measures worst-case scenario risk.',
        'sortino-tooltip': 'Risk-adjusted return considering only downside volatility. Higher is better (>2 is excellent).',
        'kelly-tooltip': 'Optimal position size based on win rate and risk/reward ratio. Recommended: use 10-25% of Kelly.',

        // NEW: Slippage Analysis
        'slippage-analysis': 'Slippage Analysis',
        'avg-slippage': 'Avg Slippage',
        'slippage-by-time': 'Slippage by Time of Day',
        'slippage-by-symbol': 'Slippage by Symbol',
        'entry-slippage': 'Entry Slippage',
        'exit-slippage': 'Exit Slippage',
        'slippage-cost': 'Slippage Cost',
        'slippage-tooltip': 'Difference between expected price and actual execution price. Lower is better.',

        // NEW: Behavioral Heatmap
        'stress-heatmap': 'Stress Level Heatmap',
        'stress-heatmap-subtitle': 'High-stress trading frequency by time and day',
        'heatmap-time': 'Time of Day',
        'heatmap-day': 'Day of Week',
        'high-risk-zone': 'High Risk Zone',
        'safe-zone': 'Safe Zone',

        // NEW: Scatter Plot Visualizations
        'position-vs-return': 'Position Size vs Return',
        'holding-vs-return': 'Holding Time vs Return',
        'scatter-winners': 'Winners',
        'scatter-losers': 'Losers',
        'regression-line': 'Trend Line',
        'scatter-tooltip': 'Each dot represents a trade. Green = profit, Red = loss.',

        // NEW: Cluster Visualization
        'cluster-2d-map': 'Trade Cluster Map',
        'cluster-best': 'Best Performance Cluster',
        'cluster-medium': 'Medium Performance Cluster',
        'cluster-worst': 'Worst Performance Cluster',
        'cluster-tooltip': 'Trades grouped by similar characteristics (holding time, P/L, entry time).',

        // NEW: Actionable Insights Categories
        'top-3-insights': 'Top 3 Actionable Insights',
        'insight-optimize': 'OPTIMIZE',
        'insight-warning': 'WARNING',
        'insight-danger': 'STOP',
        'action-required': 'Action Required',
        'immediate-action': 'Take Action Now',

        // NEW: Tooltip Definitions
        'sharpe-tooltip': 'Risk-adjusted return metric. Formula: (Avg Return - Risk-Free Rate) / Standard Deviation. >1 is good, >2 is excellent.',
        'expected-value-tooltip': 'Average profit/loss per trade based on historical data. Positive value indicates edge.',
        'p-value-tooltip': 'Statistical significance test. <0.05 means results are statistically significant (not due to chance).',
        'correlation-tooltip': 'Measures relationship between two variables. +1 = perfect positive, -1 = perfect negative, 0 = no relationship.',
        'win-rate-tooltip': 'Percentage of profitable trades. Not the only metric - consider profit factor and expected value.',
        'profit-factor-tooltip': 'Total wins / Total losses. >1.5 is good, >2 is excellent. Measures overall profitability.',

        // NEW: Core Metrics Section
        'core-metrics': 'Core Performance & Risk Metrics',
        'statistical-edge-metrics': 'Statistical Edge Analysis',
        'risk-adjusted-metrics': 'Risk-Adjusted Metrics'
    },
    ko: {
        'dashboard': '대시보드',
        'calendar': '캘린더 뷰',
        'analytics': '분석',
        'notes': '노트',
        'tradelist': '거래 목록',
        'settings': '설정',
        'dashboard-title': '트레이딩 대시보드',
        'dashboard-subtitle': '거래와 성과를 추적하세요',
        'language': '언어:',
        'total-pl': '총 손익',
        'net-result': '순 결과',
        'trades': '거래',
        'total-count': '총 개수',
        'win-rate': '승률',
        'record-trade': '거래 기록',
        'symbol': '심볼',
        'shares': '주식수',
        'buy-price': '매수 가격',
        'sell-price': '매도 가격',
        'return-pct': '수익률 %',
        'pnl': '손익',
        'entry-time': '진입 시간',
        'exit-time': '청산 시간',
        'holding-time': '보유 시간',
        'edit': '편집',
        'auto': '자동',
        'reset': '초기화',
        'add-trade': '거래 추가',
        'performance': '성과',
        'best-trade': '최고 거래',
        'worst-trade': '최악 거래',
        'avg-win': '평균 수익',
        'avg-loss': '평균 손실',
        'total-invested': '총 투자금',
        'profit-factor': '수익 팩터',
        'trade-history': '거래 내역',
        'date': '날짜',
        'time': '시간',
        'actions': '작업',
        'no-trades': '아직 기록된 거래가 없습니다',
        'calendar-title': '캘린더 뷰',
        'calendar-subtitle': '시간에 따른 거래 성과를 시각화하세요',
        'clear-selection': '선택 해제',
        'calendar-help': '캘린더에서 클릭 및 드래그로 날짜 범위를 선택하거나, 하루를 클릭하여 세부정보를 확인하세요.',
        'selected-period': '선택된 기간',
        'total-trades': '총 거래',
        'avg-daily-pl': '일일 평균 손익',
        'best-day': '최고의 날',
        'worst-day': '최악의 날',
        'weekly-pl': '주간 손익',
        'analytics-title': '트레이딩 분석',
        'notes-title': '트레이딩 노트',
        'notes-subtitle': '트레이딩 인사이트와 생각을 기록하세요',
        'new-note': '새 노트',
        'note-title-placeholder': '노트 제목을 입력하세요...',
        'note-content-placeholder': '여기에 노트를 작성하세요...',
        'cancel': '취소',
        'save-note': '노트 저장',
        'no-notes': '아직 작성된 노트가 없습니다. "새 노트"를 클릭하여 시작하세요.',
        'daily-review': '일일 리뷰',
        'strategy': '전략',
        'general': '일반',
        'no-daily-notes': '일일 리뷰 노트가 아직 없습니다. "새 노트"를 클릭하여 시작하세요.',
        'no-strategy-notes': '전략 노트가 아직 없습니다. "새 노트"를 클릭하여 시작하세요.',
        'no-general-notes': '일반 노트가 아직 없습니다. "새 노트"를 클릭하여 시작하세요.',
        'tradelist-title': '거래 목록',
        'tradelist-subtitle': '모든 거래의 완전한 목록',
        'settings-title': '설정',
        'settings-subtitle': '거래 저널 설정을 구성하세요',
        'general-settings': '일반 설정',
        'default-language': '기본 언어',
        'data-management': '데이터 관리',
        'export-data': '데이터 내보내기',
        'import-data': '데이터 가져오기',
        'import-broker-data': '브로커 데이터 가져오기',
        'import-broker-description': '브로커의 거래 내역을 업로드하세요 (CSV 또는 JSON 형식)',
        'import-broker-button': '📥 브로커 CSV/JSON 가져오기',
        'import-preview-title': '가져오기 미리보기',
        'confirm-import': '✓ 가져오기 확인',
        'danger-zone': '위험 구역',
        'clear-all-data': '모든 데이터 삭제',
        'all-time': '전체 기간',
        'this-month': '이번 달',
        'this-week': '이번 주',
        'today': '오늘',
        'detail': '상세',
        'charts': '차트',
        'net-profit': '순이익',
        'largest-win': '최대 수익',
        'largest-loss': '최대 손실',
        'performance-summary': '성과 요약',
        'trading-performance': '거래 성과',
        'total-gain': '총 수익',
        'total-loss': '총 손실',
        'total-fees': '총 수수료',
        'total-volume': '총 거래량',
        'win-loss-stats': '승패 통계',
        'winning-trades': '수익 거래',
        'losing-trades': '손실 거래',
        'avg-winning-trade': '평균 수익 거래',
        'avg-losing-trade': '평균 손실 거래',
        'daily-performance': '일일 성과',
        'daily-per-win': '승리당 일일 손익',
        'daily-per-loss': '패배당 일일 손익',
        'daily-per-fees': '일당 수수료',
        'best-trading-day': '최고 거래일',
        'worst-trading-day': '최악 거래일',
        'time-analysis': '시간 분석',
        'avg-hold-time': '평균 보유시간',
        'shortest-hold': '최단 보유',
        'longest-hold': '최장 보유',
        'best-trading-hour': '최고 거래시간',
        'worst-trading-hour': '최악 거래시간',
        'best-day-week': '최고 요일',
        'trading-activity': '거래 활동',
        'trading-days': '거래일수',
        'avg-trades-per-day': '일평균 거래수',
        'max-trades-day': '일최대 거래수',
        'avg-position-size': '평균 포지션 크기',
        'largest-position': '최대 포지션',
        'smallest-position': '최소 포지션',
        'streak-analysis': '연속성 분석',
        'current-streak': '현재 연속',
        'max-win-streak': '최대 연승',
        'max-loss-streak': '최대 연패',
        'current-win-streak': '현재 연승',
        'current-loss-streak': '현재 연패',
        'avg-win-streak': '평균 연승',
        'symbol-performance': '심볼별 성과',
        'most-profitable-symbol': '최고 수익 심볼',
        'least-profitable-symbol': '최저 수익 심볼',
        'most-traded-symbol': '최다 거래 심볼',
        'unique-symbols': '고유 심볼수',
        'symbol-win-rate': '최고 심볼 승률',
        'symbol-avg-return': '최고 심볼 평균수익',
        'risk-management': '리스크 관리',
        'max-drawdown': '최대 드로다운',
        'current-drawdown': '현재 드로다운',
        'recovery-factor': '회복 팩터',
        'max-daily-loss': '최대 일손실',
        'max-daily-gain': '최대 일수익',
        'risk-reward-ratio': '평균 위험/보상',
        'daily-fees': '일일 수수료',
        'basic-charts': '기본 성과 차트',
        'cumulative-pl': '누적 손익',
        'win-loss-ratio': '승패 분포',
        'daily-pl': '일일 손익',
        'monthly-performance': '월별 성과',
        'equity-curve': '자산 곡선',
        'drawdown-chart': '드로다운 분석',
        'symbol-performance-chart': '심볼 성과',
        'time-distribution': '시간 분포',
        'return-distribution': '수익률 분포',
        'rolling-performance': '롤링 성과',
        'volume-analysis': '거래량 분석',
        'correlation-matrix': '성과 상관관계',
        'volatility-analysis': '변동성 분석',
        'risk-return-scatter': '위험-수익 산점도',
        'performance-attribution': '성과 요인분석',
        'trade-duration-analysis': '거래 기간 분석',
        'pl-heatmap': '손익 히트맵',
        'win-rate-by-time': '시간별 승률',
        'position-sizing-analysis': '포지션 크기 분석',
        'trading-efficiency-metrics': '거래 효율성 지표',
        'all-notes': '전체',
        'back': '뒤로',
        'show-more': '더보기',
        'show-less': '접기',
        'position-calculator': '포지션 계산기',
        'kelly-criterion-calculator': '켈리 기준 계산기',
        'account-balance': '계좌 잔고 ($)',
        'win-rate-input': '승률 (%)',
        'average-win': '평균 수익 ($)',
        'average-loss': '평균 손실 ($)',
        'auto-load-trade-data': '거래 이력에서 자동 계산',
        'kelly-percentage': '켈리 비율',
        'full-kelly-position': '풀 켈리 포지션',
        'quarter-kelly': '1/4 켈리 (25%)',
        'tenth-kelly': '1/10 켈리 (10%)',
        'ultra-safe': '매우 안전',
        'conservative': '보수적',
        'moderate': '보통',
        'position-analysis': '포지션 분석',
        'recommended-size': '권장 규모',
        'account-utilization': '계좌 활용률',
        'expected-value': '기댓값',
        'auto-analysis': '자동 분석',
        'recent-win-rate': '최근 승률',
        'pl-ratio': '손익 비율',
        'kelly-status': '켈리 상태',
        'safe': '안전',
        'medium': '보통',
        'high': '위험',
        'kelly-calculator': '켈리 계산기',
        'risk-calculator': '리스크 계산기',
        'risk-percentage': '리스크 비율 (%)',
        'entry-price': '진입 가격 ($)',
        'stop-loss-price': '손절 가격 ($)',
        'position-size': '포지션 크기',
        'shares-quantity': '주식 수량',
        'risk-per-share': '주당 리스크',
        'max-loss': '최대 손실',
        'breakeven-move': '손익분기 변동',
        'risk-amount': '리스크 금액',
        'kelly-strategies': '포지션 사이징 전략',
        'risk-analysis': '리스크 분석',
        'position-cost': '포지션 비용',
        'risk-ratio': '리스크 비율',
        'stop-distance': '손절 거리',
        'risk-management-calculator': '리스크 관리 계산기',
        'risk-presets': '리스크 비율',
        'trading-record': '거래 기록',
        'amount': '금액 ($)',
        'principles': '원칙',
        'principles-title': '트레이딩 원칙',
        'principles-subtitle': '거래 규칙을 정의하고 추적하세요',
        'save-principles-data': '원칙 데이터 저장',
        'reset-principles-data': '데이터 초기화',
        'account-rules': '계좌 규칙',
        'trade-details': '세부 트레이드',
        'consecutive-loss-limit': '연속 손실 제한',
        'max-single-loss': '최대 단일 손실 ($)',
        'max-position-size': '최대 포지션 크기 ($)',
        'min-risk-reward': '최소 리스크/보상 비율',
        'warning-triggers': '경고 발생',
        'warning-triggers-subtitle': '규칙 위반 및 경고 추적',
        'consecutive-loss-warning': '연속 손실',
        'single-loss-warning': '단일 손실 초과',
        'position-size-warning': '포지션 크기 초과',
        'risk-reward-warning': '리스크/보상 미달',
        'daily-target-warning': '일일 목표 달성',
        'max-loss-warning': '최대 일일 손실 도달',
        'trade-count-warning': '거래횟수 제한 도달',
        'times-triggered': '회',
        'no-warnings': '오늘 경고 없음',
        'trade-details-score': '세부 트레이드 점수',
        'rules-compliance': '규칙 준수도',
        'rules-violations': '규칙 위반',
        'principles-warnings': '원칙 경고',
        'psychology': '심리',
        'psychology-title': '트레이딩 심리',
        'psychology-subtitle': '거래 심리를 분석하고 최적화하세요',
        'daily-psychology-input': '일일 심리 입력',
        'biological-rhythm': '생체 리듬',
        'sleep-hours': '수면 시간',
        'sleep-quality': '수면 질',
        'caffeine-intake': '카페인 섭취량 (mg)',
        'energy-level': '에너지 수준',
        'time-environment': '시간 및 환경',
        'planned-start-time': '계획된 시작 시간',
        'actual-start-time': '실제 시작 시간',
        'market-delay': '시장 개장 후 지연 (분)',
        'trading-environment': '거래 환경',
        'economic-pressure': '경제적 압박',
        'account-balance-psych': '계좌 잔고 ($)',
        'pressure-level': '재정적 압박 수준',
        'daily-target': '일일 손익 목표 ($)',
        'max-daily-loss': '최대 일일 손실 한도 ($)',
        'max-trade-count': '거래횟수 제한',
        'emotional-state': '감정 상태',
        'pre-market-mood': '장 전 기분',
        'confidence-level': '자신감 수준',
        'stress-level': '스트레스 수준',
        'focus-level': '집중력 수준',
        'save-psychology-data': '심리 데이터 저장',
        'psychology-metrics': '심리 지표',
        'daily-psych-score': '일일 심리 점수',
        'sleep-factor': '수면 요인',
        'stress-factor': '스트레스 요인',
        'environment-factor': '환경 요인',
        'pressure-index': '압박 지수',
        'emotional-readiness': '감정적 준비도',
        'psychology-insights': '심리 인사이트 및 권장사항',
        'no-psychology-data': '심리 데이터가 없습니다. 오늘의 데이터를 입력하여 인사이트를 받아보세요.',
        'start-time': '시작 시간',
        'reset-psychology-data': '데이터 초기화',
        'psychology-analysis': '심리 분석',
        'annual-trading-overview': '연간 거래 개요',
        'week-pnl': '주간 손익',
        'view-full-month': '전체 월 캘린더 보기',
        'month-details': '월별 상세',
        'close': '닫기',
        'weekly-summary': '주간 요약',
        'selected-week': '선택된 주',
        'week-trades': '주간 거래',
        'week-win-rate': '주간 승률',
        'week-best-day': '최고의 날',
        'week-worst-day': '최악의 날',
        'week-trade-details': '주간 거래 세부사항',
        'cost-basis': '평균단가',
        'trade-count': '거래',
        'delete-selected': '선택된 거래 삭제',
        'daily-input': '일일 입력',
        'metrics-dashboard': '지표 대시보드',
        'bias-analysis': '편향 분석',
        'algorithmic-analysis': '알고리즘 분석',
        'daily-data-input': '일일 데이터 입력',
        'biological-data': '생체 데이터',
        'screen-time': '거래 전 스크린 타임 (시간)',
        'planned-start': '계획된 시작 시간',
        'actual-start': '실제 시작 시간',
        'environment-type': '환경 유형',
        'distractions': '방해 요소 횟수',
        'financial-pressure': '재정적 압박 수준 (1-5)',
        'predictions': '장전 예측',
        'predicted-win-rate': '예상 승률 (%)',
        'planned-trades': '계획된 거래 수',
        'planned-position-size': '계획된 평균 포지션 크기 ($)',
        'calculate-score': '일일 점수 계산',
        'psychology-dashboard': '심리 대시보드',
        'daily-psychology-score': '일일 심리 점수',
        'discipline-factor': '규율 요인',
        'consistency-factor': '일관성 요인',
        'total-score': '총점',
        'weekly-bias-risk': '주간 편향 위험 평가',
        'overconfidence-risk': '과신 위험',
        'loss-aversion-risk': '손실 회피 위험',
        'anchoring-risk': '앵커링 위험',
        'performance-correlation': '성과 상관관계 분석',
        'sleep-performance': '수면 vs 성과',
        'caffeine-performance': '카페인 vs 성과',
        'timing-performance': '타이밍 vs 성과',
        'confidence-performance': '자신감 vs 성과',
        'bias-analysis-title': '정량화된 편향 분석',
        'overconfidence-bias': '과신 편향',
        'loss-aversion-bias': '손실 회피 편향',
        'anchoring-bias': '앵커링 편향',
        'calibration-error': '캘리브레이션 오차',
        'overtrading-index': '과도거래 지수',
        'position-deviation': '포지션 크기 편차',
        'disposition-ratio': '처분 효과 비율',
        'stop-loss-execution': '손절매 실행률',
        'stop-loss-modification': '손절매 수정률',
        'entry-price-dependency': '진입가 의존도',
        'round-number-bias': '라운드 넘버 편향',
        'recent-high-anchor': '최근 고점 앵커',
        'weekly-risk-summary': '주간 위험 요약',
        'overall-bias-risk': '전체 편향 위험',
        'risk-trend': '위험 추세',
        'action-needed': '필요한 조치',
        'end-time': '종료 시간',
        'environment-score': '환경 점수',
        'risk-assessment': '위험 평가',
        'time-based-performance': '시간대별 성과 분석',
        'optimal-sleep-range': '최적 수면 범위',
        'delay-impact': '시작 지연 영향',
        'consecutive-pattern': '연속 거래 패턴',
        'after-losses': '손실 후 성과',
        'after-wins': '수익 후 성과',
        'ai-insights': 'AI 인사이트',
        'no-insights': '더 많은 심리 데이터와 거래 기록을 수집하여 개인화된 인사이트를 생성하세요.',
        'psychology-performance-chart': '심리 vs 성과 분석',
        'algorithmic-analysis-title': '알고리즘 분석 및 인텔리전스',
        'worst-trading-hour': '최악 거래시간',
        'after-1-loss': '1회 손실 후',
        'after-2-losses': '2회 손실 후',
        'after-3-losses': '3회 이상 손실 후',
        'after-1-win': '1회 수익 후',
        'after-2-wins': '2회 수익 후',
        'after-3-wins': '3회 이상 수익 후',
        'win-rate-label': '승률',
        'limit-warning-profit-title': '일일 목표 달성!',
        'limit-warning-profit-message': '축하합니다! 일일 목표 수익에 도달했습니다.',
        'limit-warning-loss-title': '일일 손실 한도 초과!',
        'limit-warning-loss-message': '경고! 최대 일일 손실 한도를 초과했습니다.',
        'limit-warning-tradecount-title': '거래횟수 한도 초과!',
        'limit-warning-tradecount-message': '오늘의 거래횟수 제한을 초과했습니다. 휴식을 취하는 것을 권장합니다.',
        'limit-warning-current': '현재 손익',
        'limit-warning-target': '일일 목표',
        'limit-warning-limit': '손실 한도',
        'limit-warning-current-count': '현재 거래',
        'limit-warning-count-limit': '제한',
        'limit-warning-ok': '확인했습니다',
        'market-data': '시장 데이터',
        'market-context': '시장 컨텍스트',
        'symbol-quotes': '종목 시세',
        'price-context': '가격 컨텍스트 분석',
        'current-price': '현재가',
        'day-change': '등락',
        'volume': '거래량',
        'open': '시가',
        'high': '고가',
        'low': '저가',
        'previous-close': '전일종가',
        'last-updated': '업데이트',
        'refresh-quotes': '시세 새로고침',
        'loading-market-data': '시장 데이터 로딩 중...',
        'api-key-settings': 'API 키 설정',
        'alpha-vantage-api-key': 'Alpha Vantage API 키',
        'save-api-key': 'API 키 저장',
        'clear-market-cache': '시장 데이터 캐시 삭제',
        'entry-position': '진입 위치',
        'exit-position': '청산 위치',
        'vs-market-high': 'vs 시장 고가',
        'vs-market-low': 'vs 시장 저가',
        'market-range': '시장 범위',
        'no-market-data': '시장 데이터 없음',
        'api-rate-limit': 'API 호출 한도에 도달했습니다. 잠시 후 다시 시도하세요.',
        'market-characteristics': '시장 특성 분석',
        'avg-float-winners': '평균 Float (수익 종목)',
        'avg-marketcap-winners': '평균 시가총액 (수익 종목)',
        'avg-beta-winners': '평균 Beta (수익 종목)',
        'symbols-analyzed': '분석된 종목 수',
        'volume-liquidity': '거래량 & 유동성',
        'high-volume-winrate': '고거래량 승률',
        'low-volume-winrate': '저거래량 승률',
        'median-volume': '중간 거래량',
        'volatility-performance': '변동성 성과',
        'high-volatility': '고변동성 (Beta > 1.5)',
        'medium-volatility': '중변동성 (1.0-1.5)',
        'low-volatility': '저변동성 (Beta < 1.0)',
        'volatility-winrate': '승률',
        'volatility-avgreturn': '평균 수익률',
        'marketcap-preference': '시가총액 선호도',
        'small-cap': '소형주 (< $2B)',
        'mid-cap': '중형주 ($2B - $10B)',
        'large-cap': '대형주 (> $10B)',
        'cap-winrate': '승률',
        'cap-avgpnl': '평균 손익',
        'cap-trades': '거래 수',
        'loading-market-analysis': '시장 분석 로딩 중...',
        'no-market-analysis': '분석을 위한 시장 데이터가 부족합니다',
        'million-shares': '백만 주',
        'billion-dollars': '십억',

        // New market analysis translations
        'intraday-performance': '장중 성과 분석',
        'intraday-20': '진입시 20%+ 상승',
        'intraday-30': '진입시 30%+ 상승',
        'intraday-50': '진입시 50%+ 상승',
        'intraday-100': '진입시 100%+ 상승',
        'sector-performance': '섹터별 성과',
        'sector': '섹터',
        'spy-correlation': 'SPY 방향성 상관관계',
        'spy-up-days': 'SPY 상승일',
        'spy-down-days': 'SPY 하락일',
        'relative-volume': '상대 거래량 상관관계',
        'high-rel-vol': '높은 상대거래량 (2.0배+)',
        'medium-rel-vol': '중간 상대거래량 (1.5-2.0배)',
        'normal-rel-vol': '일반 상대거래량 (<1.5배)',

        // Error messages
        'api-limit-reached': 'API 한도 도달',
        'data-unavailable': '데이터 없음',
        'no-api-key': 'API 키 미설정',
        'rate-limit-wait': 'API 한도 도달. 잠시만 기다려주세요...',

        // Advanced Analysis
        'entry-exit-timing': '진입/청산 타이밍 품질',
        'avg-entry-position': '평균 진입 위치',
        'avg-exit-position': '평균 청산 위치',
        'timing-score': '타이밍 점수',
        'early-entry-rate': '조기 진입 비율',
        'profit-taking-rate': '익절 실행 비율',
        'of-range': '구간 내',
        'gap-trading-performance': '갭 트레이딩 성과',
        'gap-up-winrate': '갭업 승률',
        'gap-down-winrate': '갭다운 승률',
        'large-gap-winrate': '큰 갭(5%+) 승률',
        'best-gap-range': '최적 갭 범위',
        'sector-rotation': '섹터 회전 분석',
        'top-sector': '최고 성과 섹터',
        'sector-winrate': '섹터 승률',
        'sector-avg-return': '섹터 평균 수익',
        'sector-diversity': '섹터 다양성',
        'price-level-psychology': '가격대 심리',
        'under-5-winrate': '$5 미만 승률',
        'range-5-20-winrate': '$5-$20 승률',
        'over-20-winrate': '$20 초과 승률',
        'optimal-price-range': '최적 가격대',
        'atr-correlation': '변동성 (ATR) 상관관계',
        'high-vol-winrate': '고변동성 승률',
        'low-vol-winrate': '저변동성 승률',
        'median-volatility': '중간 변동성',
        'trades-analyzed': '분석된 거래 수',

        // Algorithmic Analysis translations
        'multi-factor-attribution': '다중 요인 성과 분석',
        'feature-importance': '특성 중요도 분석',
        'psychological-state': '심리 상태',
        'market-conditions': '시장 상황',
        'performance-trend': '최근 성과 추세',
        'bias-risk': '행동 편향 리스크',
        'recommended-action': '권장 조치',
        'behavioral-patterns': '행동 패턴 인식',
        'detected-patterns': '감지된 패턴',
        'market-intelligence': '시장 컨텍스트 인텔리전스',
        'spy-correlation-analysis': 'SPY 상관관계 분석',
        'volatility-regime': '변동성 체제 분석',
        'statistical-edge': '통계적 우위 분석',
        'win-rate-significance': '승률 유의성',
        'confidence-interval': '신뢰 구간',
        'expected-value-per-trade': '거래당 기댓값',
        'kelly-optimal': '켈리 최적 포지션',
        'sharpe-ratio': '샤프 비율',
        'statistical-significance': '통계적 유의성',
        'adaptive-recommendations': '적응형 전략 권장사항',
        'high-priority': '최우선 순위',
        'optimization': '최적화',
        'risk-warning': '리스크 경고',
        'feature-impact': '영향도',
        'sample-size': '샘플',
        'current-score': '현재 점수',
        'excellent': '우수',
        'good': '양호',
        'neutral': '보통',
        'elevated': '주의',
        'critical': '위험',
        'highly-significant': '매우 유의함',
        'significant': '유의함',
        'not-significant': '유의하지 않음',
        'regime-high-vol': '고변동성 체제',
        'regime-medium-vol': '중변동성 체제',
        'regime-low-vol': '저변동성 체제',
        'regime-performance': '체제별 성과',
        'current-regime': '현재 체제',
        'best-regime': '최적 체제',
        'correlation-strength': '상관관계 강도',
        'strong-positive': '강한 양의 상관관계',
        'moderate-positive': '보통 양의 상관관계',
        'weak': '약한 상관관계',
        'moderate-negative': '보통 음의 상관관계',
        'strong-negative': '강한 음의 상관관계',
        'next-trade-probability': '다음 거래 성공 확률',
        'probability-based-on': '현재 조건 기반',
        'edge-detected': '통계적 우위 감지됨',
        'no-edge': '통계적 우위 없음',
        'quality-score': '거래 품질 점수',
        'liquidity-score': '유동성 점수',
        'timing-quality': '타이밍 품질',
        'risk-management-quality': '리스크 관리 품질',

        // Hero Dashboard 번역
        'ai-powered-badge': 'AI 기반',
        'trading-intelligence-center': '트레이딩 인텔리전스 센터',
        'hero-trade-quality': '거래 품질',
        'hero-current-score': '현재 점수',
        'hero-win-probability': '다음 승률 확률',
        'hero-recommendation': '추천',
        'hero-performance-forecast': '성과 예측',
        'hero-expected-daily': '예상 일일 손익',
        'hero-analyze-now': '지금 분석',
        'hero-predict-session': '세션 예측',
        'hero-export-report': '리포트 내보내기',
        'favorable': '유리함',
        'neutral-rec': '중립',
        'unfavorable': '불리함',
        'confidence-high': '높은 신뢰도',
        'confidence-medium': '중간 신뢰도',
        'confidence-low': '낮은 신뢰도',
        'session-outlook': '세션 전망',
        'optimal-conditions': '최적 조건',
        'proceed-cautiously': '신중히 진행',
        'high-risk-session': '고위험 세션',
        'bias-detected': '행동 편향 감지됨',
        'similar-patterns-found': '유사한 과거 패턴 발견',
        'optimal-position-sizing': '최적 포지션 크기',
        'monte-carlo-forecast': '몬테카를로 예측',
        'expected-range': '예상 범위',
        'best-case': '최선의 경우',
        'worst-case': '최악의 경우',
        'pattern-match': '패턴 매칭',
        'historical-similarity': '과거 유사도',
        'recommended-symbols': '추천 심볼',

        // 추가 Hero Dashboard 번역
        'trading-intelligence-center': 'Trading Intelligence Center',
        'hero-subtitle': '머신러닝과 행동 패턴 인식 기반 실시간 알고리즘 분석',
        'quality-badge': '품질',
        'prediction-badge': '예측',
        'forecast-badge': '전망',
        'hero-quality-label': '거래 품질 점수',
        'hero-probability-label': '승률 확률',
        'hero-forecast-label': '세션 예측',
        'confidence-label': '신뢰도:',
        'calculating-status': '계산 중...',
        'trend-from-avg': '평균 대비',
        'trend-vs-avg': '평균 대비',

        // 로딩 및 상태 메시지
        'loading-analysis': '특성 중요도 분석 로딩 중...',
        'calculating-risk': '실시간 리스크 평가 계산 중...',
        'analyzing-patterns': '거래 패턴 분석 중...',
        'analyzing-market': '시장 상황 분석 중...',
        'computing-stats': '통계적 유의성 계산 중...',
        'generating-recs': '맞춤형 권장사항 생성 중...',
        'insufficient-data-multi': '다변량 분석을 위한 데이터가 부족합니다. 심리 데이터가 있는 거래가 최소 10개 필요합니다.',

        // 새로운 AI 분석 모듈 제목
        'temporal-pattern-recognition': '시계열 패턴 인식',
        'trade-clustering-analysis': '거래 군집 분석',
        'correlation-matrix-analysis': '다변량 상관관계 분석',
        'predictive-model': '예측 성과 모델',
        'optimization-engine': '최적화 추천 엔진',

        // 상관관계 분석
        'sleep-caffeine-interaction': '수면-카페인 상호작용',
        'stress-confidence-combo': '스트레스-자신감 조합',
        'time-psychology-cross': '시간-심리 교차 분석',
        'environment-focus-correlation': '환경-집중도 상관관계',
        'correlation-coefficient': '상관계수',
        'correlation-heatmap': '상관관계 히트맵',

        // 시계열 패턴
        'weekday-weekend-diff': '평일 vs 주말 성과',
        'monthly-seasonality': '월별 계절성 패턴',
        'optimal-trading-days': '최적 거래일',
        'consecutive-day-fatigue': '연속 거래일 피로도 분석',
        'post-break-performance': '휴식 후 성과',

        // 군집 분석
        'cluster-scalping': '빠른 스캘핑 (5-30분)',
        'cluster-swing': '스윙 트레이드 (30-120분)',
        'cluster-position': '포지션 트레이드 (120분+)',
        'cluster-performance': '군집 성과',
        'optimal-cluster': '최적 군집',

        // 예측 모델
        'win-prediction-model': '승/패 예측 모델',
        'feature-importance-rank': '특성 중요도 순위',
        'threshold-analysis': '임계값 분석',
        'real-time-probability': '실시간 확률',
        'roc-curve': 'ROC 곡선',
        'prediction-accuracy': '예측 정확도',

        // 최적화
        'optimal-position-size-rec': '최적 포지션 크기',
        'optimal-time-window': '최적 시간대',
        'optimal-psychology-state': '최적 심리 상태',
        'what-if-scenario': '만약 ~라면 시나리오 분석',
        'expected-profit-range': '예상 수익 범위',
        'simulation-results': '시뮬레이션 결과'
    }
};

// ============================================
// Export for module usage (if needed)
// ============================================

if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        // State variables
        trades,
        notes,
        dailyFees,
        currentTradingDate,
        calendarDate,
        calendarStartDate,
        calendarEndDate,
        isSelecting,
        timeEditMode,
        selectedCalendarDay,
        currentLanguage,
        analyticsPeriod,
        dashboardStartDate,
        dashboardEndDate,
        analyticsStartDate,
        analyticsEndDate,
        tradesStartDate,
        tradesEndDate,
        currentAnalyticsSection,
        editingNoteId,
        currentNotesSection,
        currentViewingNoteId,
        currentTextColor,
        currentFont,
        psychologyData,
        currentPsychologySection,
        selectedWeekPnl,
        selectedTradesList,
        selectedTrades,
        currentDashboardSection,
        selectedKellyMultiplier,
        selectedMonthYear,
        selectedMonth,
        basicCharts,
        advancedCharts,
        
        // Translations
        translations
    };
}
